### ISSUE TITLE
Add Instructions to install this app in ledger devices

### ISSUE THREAD

**Issue by green-pass** [LedgerHQ/app-security-key#5]
I have Ledger Nano X (which is up to date) but I can't see this app in the app manager.
I contacted support via website and they don't know when this app will be available.

Even tho the announcement is already made on 16 MARCH https://blog.ledger.com/security-key/

What's the ETA on this being available the ledger app? and if it's too long how would one go about installing this manually?

**Comment by Anprotaku** [comment]
I think you need to enable developer mode in the ledger app settings. Then you can find the app

**Comment by xchapron-ledger** [comment]
Developer mode should not be necessary (anymore) to install the app which should be available for user of Nano x and Nano S+ device in the last OS version.
Can you see it now?
Please reopen if it's not the case.

**Comment by Drewsapple** [comment]
To the best of my knowledge, the app is not available in ledger live (2.57.0) to install on my nano x, with the most recent firmware (2.1.0).

**Comment by xchapron-ledger** [comment]
Hello @Drewsapple 
The app is no longuer listed in the Ledger Live default list.
You currently need to enable developper mode in the "Experimental settings" in order to be able to install it.
Hopefully, this might change once  https://github.com/LedgerHQ/app-security-key/pull/11 has been merged and deployed.
